// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiCw3gCG5mMBlx_mGgVPTeGrUDU9nR7HM',
    appId: '1:39182870178:web:1934d14555de49460c19fb',
    messagingSenderId: '39182870178',
    projectId: 'laptop-harbor-db',
    authDomain: 'laptop-harbor-db.firebaseapp.com',
    storageBucket: 'laptop-harbor-db.firebasestorage.app',
    measurementId: 'G-Y4W9RT1JFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIumltBP5sZWmFiOhHIW-jodtee4hfi-w',
    appId: '1:39182870178:android:96f38785b57a1f590c19fb',
    messagingSenderId: '39182870178',
    projectId: 'laptop-harbor-db',
    storageBucket: 'laptop-harbor-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDskyyofd2R0CPSrceJQ4WGnVHaSsOKK94',
    appId: '1:39182870178:ios:1657f61e33b97fdb0c19fb',
    messagingSenderId: '39182870178',
    projectId: 'laptop-harbor-db',
    storageBucket: 'laptop-harbor-db.firebasestorage.app',
    iosBundleId: 'com.example.laptorHarbor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDskyyofd2R0CPSrceJQ4WGnVHaSsOKK94',
    appId: '1:39182870178:ios:1657f61e33b97fdb0c19fb',
    messagingSenderId: '39182870178',
    projectId: 'laptop-harbor-db',
    storageBucket: 'laptop-harbor-db.firebasestorage.app',
    iosBundleId: 'com.example.laptorHarbor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiCw3gCG5mMBlx_mGgVPTeGrUDU9nR7HM',
    appId: '1:39182870178:web:44dd39cd7ae1f40f0c19fb',
    messagingSenderId: '39182870178',
    projectId: 'laptop-harbor-db',
    authDomain: 'laptop-harbor-db.firebaseapp.com',
    storageBucket: 'laptop-harbor-db.firebasestorage.app',
    measurementId: 'G-MJDGJ6HJGE',
  );
}
